'use strict'
import * as d3 from 'd3'

export default function (params) {
  d3.select('main').append('form')

  const inputItems = d3.select('form')
    .selectAll('dl')
    .data(params)
    .enter()
    .append('dl')
    .attr('id', function (d) { return d.name })
    .attr('class', 'parameter')

  inputItems.append('label')
    .attr('class', 'value')
    .attr('for', function (d) { return d.name })
    .text(function (d) { return d.value })

  inputItems.append('dt')
    .append('label')
    .attr('class', 'name')
    .attr('for', function (d) { return d.name })
    .html(function (d) { return d.label })

  const inputRanges = inputItems.append('dd')
    .attr('class', 'param_range')
  inputRanges.append('input')
    .attr('type', 'range')
    .attr('name', function (d) { return d.name })
    .attr('min', function (d) { return d.min })
    .attr('max', function (d) { return d.max })
    .attr('step', function (d) { return d.step })
    .attr('value', function (d) { return d.value })
    .on('input', function (event, d) {
      d3.select('#' + this.name + ' label.value')
        .text(this.value)
      d.value = this.value
    })
  inputRanges.append('label')
    .attr('class', 'min')
    .attr('for', function (d) { return d.name })
    .text(function (d) { return d.min })
  inputRanges.append('label')
    .attr('class', 'max')
    .attr('for', function (d) { return d.name })
    .text(function (d) { return d.max })

  const inputModel = d3.select('form')
    .append('dl').attr('class', 'parameter')
  inputModel.append('dt').append('label')
    .attr('class', 'name')
    .text('Model')
  inputModel.append('dd')
    .each(function () {
      d3.select(this).append('input').attr('type', 'radio').attr('name', 'model')
        .attr('value', 'wrightFisherHaploid')
        .attr('id', 'wrightFisherHaploid')
        .property('checked', true)
      d3.select(this).append('label').attr('class', 'radio')
        .attr('for', 'wrightFisherHaploid')
        .text('Wright-Fisher haploid')
      d3.select(this).append('br')
      d3.select(this).append('input').attr('type', 'radio').attr('name', 'model')
        .attr('value', 'wrightFisherDiploid')
        .attr('id', 'wrightFisherDiploid')
      d3.select(this).append('label').attr('class', 'radio')
        .attr('for', 'wrightFisherDiploid')
        .text('Wright-Fisher diploid (h=0.5)')
      d3.select(this).append('br')
      d3.select(this).append('input').attr('type', 'radio').attr('name', 'model')
        .attr('value', 'heterozygoteAdvantage')
        .attr('id', 'heterozygoteAdvantage')
      d3.select(this).append('label').attr('class', 'radio')
        .attr('for', 'heterozygoteAdvantage')
        .text('Wright-Fisher heterozygote advantage')
      d3.select(this).append('br')
      d3.select(this).append('input').attr('type', 'radio').attr('name', 'model')
        .attr('value', 'moranHaploid')
        .attr('id', 'moranHaploid')
      d3.select(this).append('label').attr('class', 'radio')
        .attr('for', 'moranHaploid')
        .text('Moran haploid')
    })

  d3.select('form').append('button')
    .attr('type', 'button')
    .attr('class', 'start button')
    .text('START!')
}
